In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000


In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7409, 781, 3436, 1088],
 [7409, 781, 3436, 6285],
 [7409, 74, 3436, 3736],
 [7153, 4651, 4862, 3764, 1805],
 [7153, 4651, 4862, 3764, 1912],
 [7754, 7409, 7518, 3436, 8177],
 [1980, 3703, 408, 3764]]

In [8]:

## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential



In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7409  781 3436 1088]
 [   0    0    0    0 7409  781 3436 6285]
 [   0    0    0    0 7409   74 3436 3736]
 [   0    0    0 7153 4651 4862 3764 1805]
 [   0    0    0 7153 4651 4862 3764 1912]
 [   0    0    0 7754 7409 7518 3436 8177]
 [   0    0    0    0 1980 3703  408 3764]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 116ms/step


array([[[-0.04783016,  0.00284034, -0.01464828,  0.04496049,
         -0.01644333,  0.01428122,  0.03679444, -0.04066311,
         -0.00795277, -0.03139194],
        [-0.04783016,  0.00284034, -0.01464828,  0.04496049,
         -0.01644333,  0.01428122,  0.03679444, -0.04066311,
         -0.00795277, -0.03139194],
        [-0.04783016,  0.00284034, -0.01464828,  0.04496049,
         -0.01644333,  0.01428122,  0.03679444, -0.04066311,
         -0.00795277, -0.03139194],
        [-0.04783016,  0.00284034, -0.01464828,  0.04496049,
         -0.01644333,  0.01428122,  0.03679444, -0.04066311,
         -0.00795277, -0.03139194],
        [ 0.01970233,  0.043723  ,  0.01584486,  0.03405816,
         -0.02622288,  0.02295984,  0.02611331,  0.00676867,
          0.04404875, -0.02871083],
        [-0.03259586,  0.03897179, -0.04528327,  0.03819707,
          0.02606289,  0.00597417,  0.01479833, -0.0016172 ,
          0.03777435,  0.03663502],
        [-0.04161427,  0.04687205, -0.03570461, -0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 7409,  781, 3436, 1088])

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 30ms/step


array([[-0.04783016,  0.00284034, -0.01464828,  0.04496049, -0.01644333,
         0.01428122,  0.03679444, -0.04066311, -0.00795277, -0.03139194],
       [-0.04783016,  0.00284034, -0.01464828,  0.04496049, -0.01644333,
         0.01428122,  0.03679444, -0.04066311, -0.00795277, -0.03139194],
       [-0.04783016,  0.00284034, -0.01464828,  0.04496049, -0.01644333,
         0.01428122,  0.03679444, -0.04066311, -0.00795277, -0.03139194],
       [-0.04783016,  0.00284034, -0.01464828,  0.04496049, -0.01644333,
         0.01428122,  0.03679444, -0.04066311, -0.00795277, -0.03139194],
       [ 0.01970233,  0.043723  ,  0.01584486,  0.03405816, -0.02622288,
         0.02295984,  0.02611331,  0.00676867,  0.04404875, -0.02871083],
       [-0.03259586,  0.03897179, -0.04528327,  0.03819707,  0.02606289,
         0.00597417,  0.01479833, -0.0016172 ,  0.03777435,  0.03663502],
       [-0.04161427,  0.04687205, -0.03570461, -0.03265138, -0.02911993,
        -0.00711385,  0.03406763,  0.01299078